### ISSUE TITLE
Is it possible to send command-line arguments to Sauce Labs browsers?

### ISSUE THREAD

**Issue by jzombie** [airtap/sauce#10]
Was experimenting with trying to get Chrome to launch in incognito mode on Sauce Labs and couldn't figure out how to do it either with command-line args or with capabilities object.

Nothing seemed to have any effect.

--

Using sauce-system, I was able to make it work just fine, however, though I had to make a PR to update the README on how to make it work right:  https://github.com/airtap/airtap/pull/314

--

What I'm actually trying to do is start Chrome w/  --autoplay-policy=no-user-gesture-required, in order to test some audio media, and would like to try to find the equivalent of how to do that in iOS simulator as well, if it's possible.

**Comment by vweevers** [comment]
I'd start by looking for relevant options in Sauce Labs documentation. If there are any, we can see how to expose them here.
